server:
  port: 8090

lowres:
  queueName: lowres

highres:
  queueName: highres

thumbnail:
  queueName: thumbnail

sqs:
  regionName: us-east-1

s3:
  bucket: geekoosh-aws-sqs
  workingFolder: /tmp

multipart:
  maxFileSize: 2000KB
  maxRequestSize: 2000KB

spring:
  datasource:
    url: jdbc:mysql://video.cgholfkyyxdg.us-east-1.rds.amazonaws.com:3306/video
    username: video
    password: video123456
    testWhileIdle: true
    validationQuery: SELECT 1

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect

---

spring:
  profiles: local
  datasource:
    url: jdbc:mysql://localhost:3306/video